apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-backend
  namespace: default
spec:
  replicas: 2
  selector: { matchLabels: { app: auction-backend } }
  template:
    metadata: { labels: { app: auction-backend } }
    spec:
      containers:
      - name: backend
        image: ghcr.io/donneypr/eecs4413_auction-backend:latest
        ports: [{ containerPort: 8000 }]
        env:
        - name: TZ                      ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: TZ}}
        - name: DJANGO_DEBUG            ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: DJANGO_DEBUG}}
        - name: DJANGO_ALLOWED_HOSTS    ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: DJANGO_ALLOWED_HOSTS}}
        - name: DJANGO_CSRF_TRUSTED_ORIGINS ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: DJANGO_CSRF_TRUSTED_ORIGINS}}
        - name: DJANGO_SECRET_KEY       ; valueFrom: {secretKeyRef: {name: auction-secrets, key: DJANGO_SECRET_KEY}}
        - name: MYSQL_DATABASE          ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: MYSQL_DATABASE}}
        - name: MYSQL_USER              ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: MYSQL_USER}}
        - name: MYSQL_HOST              ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: MYSQL_HOST}}
        - name: MYSQL_PORT              ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: MYSQL_PORT}}
        - name: MYSQL_PASSWORD          ; valueFrom: {secretKeyRef: {name: auction-secrets, key: MYSQL_PASSWORD}}
        command: ["gunicorn"]
        args: ["core.wsgi:application","--bind","0.0.0.0:8000","--workers","3","--timeout","90"]
        readinessProbe:
          httpGet: { path: "/health/", port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket: { port: 8000 }
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
spec:
  selector: { app: auction-backend }
  ports: [{ port: 8000, targetPort: 8000 }]