apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-frontend
  namespace: default
spec:
  replicas: 3
  selector: { matchLabels: { app: auction-frontend } }
  template:
    metadata: { labels: { app: auction-frontend } }
    spec:
      containers:
      - name: frontend
        image: ghcr.io/donneypr/eecs4413_auction-frontend:latest 
        ports: [{ containerPort: 3000 }]
        env:
        - name: TZ                      ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: TZ}}
        - name: NEXT_PUBLIC_API_BASE    ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: NEXT_PUBLIC_API_BASE}}
        - name: API_BASE_INTERNAL       ; valueFrom: {configMapKeyRef: {name: auction-app-config, key: API_BASE_INTERNAL}}
        readinessProbe:
          httpGet: { path: "/", port: 3000 }
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: default
spec:
  selector: { app: auction-frontend }
  ports: [{ port: 3000, targetPort: 3000 }]