apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: default
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/donneypr/eecs4413_auction-backend:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: TZ
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: DJANGO_DEBUG
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: DJANGO_ALLOWED_HOSTS
            - name: DJANGO_CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: DJANGO_CSRF_TRUSTED_ORIGINS
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auction-secrets
                  key: DJANGO_SECRET_KEY
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: MYSQL_USER
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: auction-app-config
                  key: MYSQL_PORT
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auction-secrets
                  key: MYSQL_PASSWORD
          command: ["sh","-lc"]
          args:
            - |
              echo "Waiting for MySQL at ${MYSQL_HOST}:${MYSQL_PORT}..."
              until nc -z "$MYSQL_HOST" "$MYSQL_PORT"; do sleep 2; done
              python manage.py migrate --noinput