apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
spec:
  replicas: 2
  selector: { matchLabels: { app: hello } }
  template:
    metadata: { labels: { app: hello } }
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports: [{ containerPort: 80 }]
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap: { name: hello-html }
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  selector: { app: hello }
  ports: [{ port: 80, targetPort: 80 }]
