# Generated by Django 5.2.7 on 2025-10-31 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_type', models.CharField(choices=[('FORWARD', 'Forward'), ('DUTCH', 'Dutch')], max_length=10)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                # Fields from 0002
                ('bid_history', models.JSONField(blank=True, default=list)),
                ('current_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bidding_on', to=settings.AUTH_USER_MODEL)),
                ('dutch_decrease_interval', models.IntegerField(blank=True, help_text='Minutes between price decreases', null=True)),
                ('dutch_decrease_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage to decrease price (e.g., type 5.00 for 5%, 10.00 for 10%)', max_digits=5, null=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                # Fields from 0003
                ('expedited_shipping_cost', models.DecimalField(decimal_places=2, default=20.0, help_text='Additional cost for expedited shipping cost', max_digits=10)),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=15.0, help_text='Standard shipping cost', max_digits=10)),
                # Foreign key to seller
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_selling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
