# Generated by Django 5.2.7 on 2025-10-31 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bid_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='current_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bidding_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='dutch_decrease_interval',
            field=models.IntegerField(blank=True, help_text='Minutes between price decreases', null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='dutch_decrease_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage to decrease price (e.g., type 5.00 for 5%, 10.00 for 10%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
