# Generated by Django 5.2.8 on 2025-11-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of base64-encoded images with metadata'),
        ),
    ]
