# Generated by Django 5.2.7 on 2025-10-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_bid_history_auctionitem_current_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='expedited_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Additional cost for expedited shipping cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='standard_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Standard shipping cost', max_digits=10),
        ),
    ]
