# Generated by Django 5.2.8 on 2025-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='dutch_decrease_interval',
            field=models.IntegerField(blank=True, help_text='Time interval in seconds for price decrease', null=True),
        ),
    ]
